### PR TITLE
cli_app.js  set --min-confirmations to 0 for now

### PR DESCRIPTION
**Pull request by assafmo**

### CODE REVIEW

**Comment by lacabra** [comment]
Looks good, but the builds will break until enigmampc/enigma-p2p#251 is merged, as currently the p2p nodes cannot start because of this error: ` error: unknown option `--min-confirmations'`

**Review by lacabra — APPROVED** [review]

**Comment by lenak25** [comment]
@lacabra shouldn't we then align these two PR's names?

**Comment by lacabra** [comment]
@lenak25 it does not work like this in this case. The branch sync for CIs only happens currently between core, contract and p2p. It would easy to add this repo, but right now it is not.

I have limited (or no) time to work on this this week. I suggest that we run this test offline to verify that works, or if you are confident it works, go with it, merge this one to master, and then rerun the CI for p2p, knowing the between this merge and p2p merge, the other CI will be temp broken

**Comment by assafmo** [comment]
@lacabra  No worries, we'll merge it in p2p and only then here.

**Pull request closed without merging**
